# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/pantech/ef65l/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
	vendor/pantech/ef65l/proprietary/lib/libacdbloader.so:obj/lib/libacdbloader.so \
	vendor/pantech/ef65l/proprietary/lib/libacdbmapper.so:obj/lib/libacdbmapper.so \
	vendor/pantech/ef65l/proprietary/lib/libaudioalsa.so:obj/lib/libaudioalsa.so \
	vendor/pantech/ef65l/proprietary/lib/libcamera.so:obj/lib/libcamera.so \
	vendor/pantech/ef65l/proprietary/lib/libril.so:obj/lib/libril.so

# Device-specific proprietary files
PRODUCT_COPY_FILES += \
	vendor/pantech/ef65l/proprietary/lib/libpn544_fw.so:system/lib/libpn544_fw.so \
	vendor/pantech/ef65l/proprietary/etc/wl/nvram.txt:system/etc/wl/nvram.txt

# Device family proprietary files
PRODUCT_COPY_FILES += \
        vendor/pantech/ef65l/proprietary/bin/bridgemgrd:system/bin/bridgemgrd \
        vendor/pantech/ef65l/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
        vendor/pantech/ef65l/proprietary/bin/mpdecision:system/bin/mpdecision \
        vendor/pantech/ef65l/proprietary/bin/port-bridge:system/bin/port-bridge \
        vendor/pantech/ef65l/proprietary/bin/usbhub:system/bin/usbhub \
        vendor/pantech/ef65l/proprietary/bin/usbhub_init:system/bin/usbhub_init \
        vendor/pantech/ef65l/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
        vendor/pantech/ef65l/proprietary/lib/libacdbmapper.so:system/lib/libacdbmapper.so \
        vendor/pantech/ef65l/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
        vendor/pantech/ef65l/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
        vendor/pantech/ef65l/proprietary/lib/libaudioparsers.so:system/lib/libaudioparsers.so \
        vendor/pantech/ef65l/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
        vendor/pantech/ef65l/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
        vendor/pantech/ef65l/proprietary/lib/libmmparser_divxdrmlib.so:system/lib/libmmparser_divxdrmlib.so \
        vendor/pantech/ef65l/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
        vendor/pantech/ef65l/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
        vendor/pantech/ef65l/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
        vendor/pantech/ef65l/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
        vendor/pantech/ef65l/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
        vendor/pantech/ef65l/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
        vendor/pantech/ef65l/proprietary/lib/libgsl.so:system/lib/libgsl.so \
        vendor/pantech/ef65l/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
        vendor/pantech/ef65l/proprietary/bin/ks:system/bin/ks \
        vendor/pantech/ef65l/proprietary/bin/netmgrd:system/bin/netmgrd \
        vendor/pantech/ef65l/proprietary/bin/qcks:system/bin/qcks \
        vendor/pantech/ef65l/proprietary/bin/qmiproxy:system/bin/qmiproxy \
        vendor/pantech/ef65l/proprietary/bin/qmuxd:system/bin/qmuxd \
        vendor/pantech/ef65l/proprietary/bin/rild:system/bin/rild \
        vendor/pantech/ef65l/proprietary/bin/rmt_storage:system/bin/rmt_storage \
        vendor/pantech/ef65l/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
        vendor/pantech/ef65l/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
        vendor/pantech/ef65l/proprietary/lib/libidl.so:system/lib/libidl.so \
        vendor/pantech/ef65l/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
        vendor/pantech/ef65l/proprietary/lib/libqdp.so:system/lib/libqdp.so \
        vendor/pantech/ef65l/proprietary/lib/libqmi.so:system/lib/libqmi.so \
        vendor/pantech/ef65l/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
        vendor/pantech/ef65l/proprietary/lib/libqueue.so:system/lib/libqueue.so \
        vendor/pantech/ef65l/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
        vendor/pantech/ef65l/proprietary/lib/libril.so:system/lib/libril.so \
        vendor/pantech/ef65l/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
        vendor/pantech/ef65l/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
        vendor/pantech/ef65l/proprietary/lib/libuca-ril.so:system/lib/libuca-ril.so \
        vendor/pantech/ef65l/proprietary/lib/libucaril.so:system/lib/libucaril.so \
        vendor/pantech/ef65l/proprietary/lib/libtime_genoff.so:system/lib/libtime_genoff.so \
        vendor/pantech/ef65l/proprietary/lib/libcommondefs.so:system/lib/libcommondefs.so \
        vendor/pantech/ef65l/proprietary/lib/libloc_api-rpc-qc.so:system/lib/libloc_api-rpc-qc.so \
        vendor/pantech/ef65l/proprietary/lib/libloc_ext.so:system/lib/libloc_ext.so \
        vendor/pantech/ef65l/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
        vendor/pantech/ef65l/proprietary/lib/hw/sensors.msm8660.so:system/lib/hw/sensors.msm8660.so \
        vendor/pantech/ef65l/proprietary/lib/libmpl.so:system/lib/libmpl.so \
        vendor/pantech/ef65l/proprietary/lib/libmlplatform.so:system/lib/libmlplatform.so \
        vendor/pantech/ef65l/proprietary/lib/libmllite.so:system/lib/libmllite.so \
        vendor/pantech/ef65l/proprietary/lib/hw/lights.msm8660.so:system/lib/hw/lights.msm8660.so \
        vendor/pantech/ef65l/proprietary/lib/libcamera.so:system/lib/libcamera.so \
        vendor/pantech/ef65l/proprietary/lib/libgemini.so:system/lib/libgemini.so \
        vendor/pantech/ef65l/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
        vendor/pantech/ef65l/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
        vendor/pantech/ef65l/proprietary/lib/libmmmpo.so:system/lib/libmmmpo.so \
        vendor/pantech/ef65l/proprietary/lib/libmmstereo.so:system/lib/libmmstereo.so \
        vendor/pantech/ef65l/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
        vendor/pantech/ef65l/proprietary/lib/libdiag.so:system/lib/libdiag.so \
        vendor/pantech/ef65l/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
        vendor/pantech/ef65l/proprietary/etc/wl/bcm4330.bin:system/etc/wl/bcm4330.bin \
        vendor/pantech/ef65l/proprietary/etc/wl/bcm4330_apsta.bin:system/etc/wl/bcm4330_apsta.bin \
        vendor/pantech/ef65l/proprietary/etc/wl/bcm4330_mfg.bin:system/etc/wl/bcm4330_mfg.bin \
        vendor/pantech/ef65l/proprietary/etc/wl/bcm4330_p2p.bin:system/etc/wl/bcm4330_p2p.bin \
        vendor/pantech/ef65l/proprietary/etc/wl/nvram.txt:system/etc/wl/nvram.txt \
        vendor/pantech/ef65l/proprietary/etc/firmware/cyttsp_8660_ffa.hex:system/etc/firmware/cyttsp_8660_ffa.hex \
        vendor/pantech/ef65l/proprietary/etc/firmware/cyttsp_8660_fluid_p2.hex:system/etc/firmware/cyttsp_8660_fluid_p2.hex \
        vendor/pantech/ef65l/proprietary/etc/firmware/cyttsp_8660_fluid_p3.hex:system/etc/firmware/cyttsp_8660_fluid_p3.hex \
        vendor/pantech/ef65l/proprietary/etc/firmware/dsps_fluid.b00:system/etc/firmware/dsps_fluid.b00 \
        vendor/pantech/ef65l/proprietary/etc/firmware/dsps_fluid.b01:system/etc/firmware/dsps_fluid.b01 \
        vendor/pantech/ef65l/proprietary/etc/firmware/dsps_fluid.b02:system/etc/firmware/dsps_fluid.b02 \
        vendor/pantech/ef65l/proprietary/etc/firmware/dsps_fluid.b03:system/etc/firmware/dsps_fluid.b03 \
        vendor/pantech/ef65l/proprietary/etc/firmware/dsps_fluid.mdt:system/etc/firmware/dsps_fluid.mdt \
        vendor/pantech/ef65l/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
        vendor/pantech/ef65l/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
        vendor/pantech/ef65l/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
        vendor/pantech/ef65l/proprietary/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
        vendor/pantech/ef65l/proprietary/etc/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw
